# Copie este arquivo para "application-local.properties" (ja ignorado no .gitignore)
# e sobrescreva as credenciais reais do seu ambiente.
spring.datasource.username=postgres
spring.datasource.password=#Jam271324$
